### ISSUE TITLE
Words with colons incorrectly render to links

### ISSUE THREAD

**Issue by sooda** [flying-sheep/rust-rst#18]
Some standalone hyperlinks are intended to be recognized and rendered into clickable links. However, some text that just remotely resembles a link seems to be parsed into a link, e.g. `foo:bar`.

This seems to be caused by the arbitrary link scheme in the parser being too permissive.

Compared to docs from https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html

> The scheme is the name of the protocol, such as "http", "ftp", "mailto", or "telnet". The scheme consists of an initial letter, followed by letters, numbers, and/or "+", "-", ".". Recognition is limited to known schemes, per the Official IANA Registry of URI Schemes and the W3C's Retired Index of WWW Addressing Schemes.

**Comment by sooda** [comment]
See PR #19 for an executable demo.

**Comment by flying-sheep** [comment]
Fixed by #19
