### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by ryanhiebert** [flying-sheep/rust-rst#2]
The Readme states that it is "dual-licensed under Apache 2.0 and MIT", but the `Cargo.toml` says the license is "GPL-3.0". The GPL is the one that's showing up on crates.io. They should be made to match each other. Preferable under the dual-license, if you wanted my opinion, as I suspect that GPL would hamper distribution in the Rust community, and I suspect that it's what you already intended.

**Comment by flying-sheep** [comment]
i generally license most stuff under GPL 3, but my rust stuff under that usual dual license.

good call.

also good waking call to work on this again!

**Comment by ryanhiebert** [comment]
If there's some low-hanging fruit, make a couple issues, and I'll see if I can help. Right now my current task is to read through and understand the code...

**Comment by flying-sheep** [comment]
there’s only one high-hanging one: there’s no parser yet.
