### ISSUE TITLE
Finish up comments

### ISSUE THREAD

**Issue by flying-sheep** [flying-sheep/rust-rst#26]
Hey @nitnelave!

Following up on #23:

Master currently panics when encountering:

```restructuredtext
.. Comments can also be
   run-in like this
```

`convert_comment` encounters a `Rule::comment_line`, because you indiscriminately skip and unwrap instead of handling all prossibilities:

```pest
block_comment   = {
    ".." ~ PUSH(" "*) ~ comment_title? ~ NEWLINE? ~ comment_block? ~ (" "* ~ NEWLINE)* ~ DROP
}
comment_title      = { (!NEWLINE ~ ANY)+ }
comment_block      = { (comment_line_blank* ~ PEEK[..] ~ comment_line)+ }
comment_line_blank = { " "* ~ NEWLINE }
comment_line       = { " "+ ~ (!NEWLINE ~ ANY)+ ~ NEWLINE }
```

I think we should just get rid of the title. Comments are just text, we can just have the rules be `block_comment { (comment_line_blank | comment_line)+ }`

**Comment by nitnelave** [comment]
If we want to be able to exactly reproduce the parsed comment, we shouldn't get rid of the title, I think. Can you tell exactly where is the problematic unwrap? I can handle the missing cases.

**Comment by flying-sheep** [comment]
We can just treat the “title” as another line, only that it isn’t indented. Something like:

```pest
block_comment   = {
    ".." ~ PUSH(" "*) ~ comment_content ~ (" "* ~ NEWLINE)* ~ DROP
}
comment_content    = _{ comment_line ~ (comment_line_blank* ~ PEEK[..] ~ comment_line)* }
comment_line_blank =  { " "* ~ NEWLINE }
comment_line       =  { (!NEWLINE ~ ANY)+ ~ NEWLINE }
```

**Comment by flying-sheep** [comment]
Done! re: next steps: Things already seem to work fine!
