### ISSUE TITLE
Write a parser

### ISSUE THREAD

**Issue by ryanhiebert** [flying-sheep/rust-rst#3]
As indicated in #2 , we need a parser.

Do we know what _kind_ of a parser we might like? For instance, what about a PEG parser? They've seemed pretty nice, but I don't know if a PEG parser would be sufficient for the syntax of rst.

One problem in particular for PEG is that it can't handle significant indentation. I think we may be able to get away with that by having a pre-processor that would add indentation tokens to the source, but I'm not sure that's a great way to go.

I'm interested in parsers, but I'm new to it, so any thoughts you have on what a good way to do it is would be great. Do we ultimately just have to have a state machine?

**Comment by flying-sheep** [comment]
i think there have to be at least two levels to parsing this anyway:

1. a hierarchy of local elements that can be parsed as entities
2. a document complete with resolved references (as e.g. link targets can appear anywhere in the source, independently

we can use [rust markdown parsers](https://github.com/google/pulldown-cmark) [(2)](https://github.com/netvl/md.rs) as examples, or [non-python rst parsers](http://stackoverflow.com/questions/2746692/restructuredtext-tool-support)

**Comment by flying-sheep** [comment]
We have a pest parser now, combined with a few subparsers for things like numbers and so on. No idea if that’s the best approach!
