### ISSUE TITLE
last line must be allowed to start with `.. `

### ISSUE THREAD

**Issue by getreu** [flying-sheep/rust-rst#30]
I included your renderer to my [tp-note project](https://github.com/getreu/tp-note). Thank you for sharing this.
I noticed that the file does wrongly not render, when the last line starts with `.. `. for example:

```rst
.. comment
```
or

```rst
.. _link: https://getreu.net
```

When I add some regular text behind, it renders again.

**Comment by getreu** [comment]
BTW: I mentioned your crate in a blog post: [Jens Getreu's blog - Tp-Note learns RestructuredText](https://blog.getreu.net/20201101-tp-note-news3/)

**Comment by flying-sheep** [comment]
Oh thank you!

About your test case: I think the problem was the lack of a trailing newline, as e.g. rust-rst’s README also ends with a link target.

I think  #31 should fix it!

**Comment by getreu** [comment]
> About your test case: I think the problem was the lack of a trailing newline

Yes, you are right. I observed the following:

It parses when:

1. the last line starts with `.. ` ended by one or more `\n`,
2. the last line starts with regular text ended by zero or one `\n`.

It does not parse when:

3. the last line starts with `.. ` without trailing `\n`.
4. the last line starts with regular text ended by more than one `\n`.


My current workaround is:

```rust
// To add a newline at the end, we need to copy here. No other choice.
let mut rest_input = rest_input.trim().to_string();
rest_input.push('\n');
let document = parse(rest_input.as_str()).map_err(|e| anyhow!(e))?;
```

The above `to_string()` implies allocation of memory and copying.

The following would avoid this and fix use case no. 3.:

> Or really fix this by replacing NEWLINE in the grammar with newline = _{ NEWLINE | EOI }

Together with some extra idea for use case no. 4., I could just do:

```rust
let document = parse(rest_input.trim().map_err(|e| anyhow!(e))?;
```

Or together with #32, it would look like:

```rust
let document = parse(rest_input.trim())?;
```

Or even, if you did the `trim()` at your side, then it would look like this:

```rust
let document = parse(rest_input)?;
```

**Comment by flying-sheep** [comment]
Hmm, I tried doing `sed -i 's/NEWLINE/nl/g' rst.pest` and then adding this:

```rust
nl = _{ NEWLINE | &EOI }
```

But for some reason the tests then loop infinitely. Any idea why?

**Comment by getreu** [comment]
Thank you. Unfortunately, I am not familiar with with this parser. I am afraid I can not help. Maybe try to execute step by step with a debugger to identify the loop. This sometimes gives a hint.
