### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by jelmer** [flying-sheep/rust-rst#56]
Would it be possible to do a release with the recent changes? It looks like the last one is from 2020.

**Comment by jelmer** [comment]
ping @flying-sheep

**Comment by flying-sheep** [comment]
Hi, sorry for dropping the ball on this! Would you like to become co-maintainer?

I think we should have a call before that, but I’d be up for sharing this project!

**Comment by jelmer** [comment]
Thanks for doing the release! I'd be interested in becoming co-maintainer. My experience with pest is kind of limited so I'd appreciate more reviews from you for any changes I try to make in that space.

**Comment by flying-sheep** [comment]
That also works. I think I overestimated how much fixing the release flow needs. It was actually already set up, I just needed to regenerated the token.
